# Generated by Django 4.0.3 on 2022-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_guarded_user_healed_user_wolf_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='power_usage',
            field=models.IntegerField(default=0),
        ),
    ]
