# Generated by Django 4.0.3 on 2022-04-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_power_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='death_potion',
            field=models.BooleanField(default=False),
        ),
    ]
