# Generated by Django 4.0.3 on 2022-04-05 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxplayers', models.IntegerField(default=2)),
                ('state', models.IntegerField(default=1)),
                ('currentplayers', models.IntegerField(default=0)),
                ('dayState', models.IntegerField(default=0)),
                ('dayNumber', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['maxplayers'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='VIDE')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='white', max_length=10)),
                ('state_visible', models.IntegerField(default=0)),
                ('side', models.CharField(default='ALL', max_length=10)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moerwolfgame.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
