# Generated by Django 4.0.3 on 2022-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moerwolfgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='voting_available',
            field=models.BooleanField(default=True),
        ),
    ]
