# Generated by Django 4.0.3 on 2022-04-06 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moerwolfgame', '0002_game_voting_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wolf_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='wolf_votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
