# Generated by Django 4.0.3 on 2022-04-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moerwolfgame', '0003_game_wolf_target_game_wolf_votes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='wolf_target',
        ),
        migrations.RemoveField(
            model_name='game',
            name='wolf_votes_count',
        ),
    ]
